# Generated by Django 5.1.3 on 2025-03-06 20:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
